namespace TPRandomizer
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using TPRandomizer.Util;

    public class CheckIdClass
    {
        // Do not edit idChars ever. The list index must map to the same id forever.
        private static readonly string idChars = "012345abcdefghijklmnopqrstuvwxyz";
        private static Dictionary<string, string> nameToId;
        private static Dictionary<int, string> idNumToName;

        private static HashSet<string> hideFromUiCheckNames =
            new()
            {
                "FT Diababa",
                "GM Fyrus",
                "LBT Morpheel",
                "AG Stallord",
                "SPR Blizzeta",
                "ToT Armogohma",
                "CitS Argorok",
                "PoT Zant",
                "HC Ganondorf",
                "Bridge of Eldin Portal",
                "CT Portal",
                "Death Mountain Portal",
                "Desert Portal",
                "Kak Gorge Portal",
                "Kak Village Portal",
                "Lake Hylia Portal",
                "Mirror Chamber Portal",
                "North Faron Portal",
                "Sacred Grove Portal",
                "South Faron Portal",
                "Snowpeak Portal",
                "UZR Portal",
                "ZD Portal",
            };

        static CheckIdClass()
        {
            // The names in this list match exactly with the json files in the
            // "Checks" directory. If support for a new check is ever added, add
            // the check name to the bottom of the list. This order which items
            // were placed in the list was arbitrary, but now that they are
            // there they cannot change.

            // THE ORDER OF THIS LIST MUST NEVER CHANGE. The generated item
            // placements on the server use the generated ids to determine which
            // item goes at each check, and adjusting the order would break
            // backwards compatibility with the data on the server.
            List<string> checkNames = new List<string>
            {
                "PoT East Wing Second Room Southwest Chest",
                "Faron Field Poe",
                "GM Crystal Switch Room Small Chest",
                "GM Gor Liggs Key Shard",
                "Wrestling With Bo",
                "GM After Crystal Switch Room Magnet Wall Chest",
                "Agitha Female Phasmid Reward",
                "SPR East Courtyard Buried Chest",
                "SPR Lobby East Armor Chest",
                "Bridge of Eldin Owl Statue Sky Character",
                "AG Entrance Chest",
                "HC Treasure Room Third Chest",
                "AG Torch Room Poe",
                "PoT East Wing Second Room Northwest Chest",
                "HC Graveyard Owl Statue Chest",
                "Faron Field Corner Grotto Rear Chest",
                "ZD Male Dragonfly",
                "Desert Lone Small Chest",
                "Desert Rock Grotto Lantern Chest",
                "Lake Hylia Water Toadpoli Grotto Chest",
                "Faron Mist Stump Chest",
                "Lanayru Field Poe Grotto Left Poe",
                "CitS Underwater West Chest",
                "ToT Dungeon Reward",
                "Ordon Spring Golden Wolf",
                "HC Main Hall Northeast Chest",
                "Desert Northeast Chest Behind Gates",
                "Ilia Charm",
                "Agitha Male Ladybug Reward",
                "HC Treasure Room Seventh Small Chest",
                "Lake Hylia Tower Poe",
                "AG Spinner Room Lower North Chest",
                "Sacred Grove Past Owl Statue Chest",
                "LBT Morpheel Heart Container",
                "Lost Woods Lantern Chest",
                "Lanayru Field Skulltula Grotto Chest",
                "Faron Mist Cave Lantern Chest",
                "Eldin Lantern Cave First Chest",
                "Faron Field Corner Grotto Right Chest",
                "Ordon Ranch Grotto Lantern Chest",
                "Sera Shop Slingshot",
                "LBT East Lower Waterwheel Stalactite Chest",
                "SPR Chest After Darkhammer",
                "GM Gor Liggs Chest",
                "AG East Turning Room Poe",
                "Lanayru Field Female Stag Beetle",
                "ZD Chest By Mother and Child Isles",
                "North Faron Woods Deku Baba Chest",
                "CitS Baba Tower Top Small Chest",
                "Kak Village Bomb Rock Spire Heart Piece",
                "AG Stallord Heart Container",
                "ZD Chest Behind Waterfall",
                "CitS Central Outside Ledge Chest",
                "PoT East Wing First Room West Alcove Chest",
                "Bulblin Camp First Chest Under Tower At Entrance",
                "AG West Stalfos Northeast Chest",
                "OCT South Male Ladybug",
                "Jovani 20 Poe Soul Reward",
                "BCT Helmasaur Grotto Chest",
                "ZD Underwater Goron",
                "Kak Inn Chest",
                "Agitha Female Beetle Reward",
                "Lanayru Spring Back Room Left Chest",
                "Agitha Female Grasshopper Reward",
                "CitS Baba Tower Alcove Chest",
                "GM Gor Amato Chest",
                "GM Gor Ebizo Chest",
                "Faron Mist North Chest",
                "LBT West Lower Small Chest",
                "Agitha Male Phasmid Reward",
                "CitS Chest Behind North Fan",
                "LLC Final Poe",
                "ToT Lobby Lantern Chest",
                "LBT East Second Floor Southeast Chest",
                "Hyrule Field Amphitheater Poe",
                "Desert Peahat Ledge Chest",
                "Iza Helping Hand",
                "LLC Second Chest",
                "LBT Central Room Small Chest",
                "Links Basement Chest",
                "Snowpeak Cave Ice Lantern Chest",
                "Desert Poe Above CoO",
                "Eldin Field Water Bomb Fish Grotto Chest",
                "Kak Village Watchtower Poe",
                "Agitha Female Dragonfly Reward",
                "Gift From Ralis",
                "South Faron Cave Chest",
                "LBT West Second Floor Southeast Chest",
                "ToT Darknut Chest",
                "FT Central North Chest",
                "Lanayru Field Male Stag Beetle",
                "CitS Underwater East Chest",
                "FT East Water Cave Chest",
                "HC Treasure Room Second Small Chest",
                "Lake Hylia Bridge Vines Chest",
                "CitS East Wing After Dinalfos Ledge Chest",
                "SPR Lobby Armor Poe",
                "Faron Field Tree Heart Piece",
                "Eldin Field Stalfos Grotto Right Small Chest",
                "LLC First Poe",
                "HC Treasure Room Fourth Small Chest",
                "Kak Village Malo Mart Hawkeye",
                "Uli Cradle Delivery",
                "Flight By Fowl Ledge Poe",
                "LBT West Water Supply Chest",
                "PoT East Wing Second Room Northeast Chest",
                "Kak Village Bomb Shop Poe",
                "Faron Mist Poe",
                "Lake Hylia Bridge Cliff Poe",
                "HC Main Hall Southwest Chest",
                "Wooden Sword Chest",
                "GM Dangoro Chest",
                "CitS Garden Island Poe",
                "Faron Field Female Beetle",
                "Eldin Field Male Grasshopper",
                "Desert Rock Grotto First Poe",
                "Eldin Lantern Cave Second Chest",
                "PoT West Wing Second Room Southeast Chest",
                "AG East Upper Turnable Redead Chest",
                "Sacred Grove ToT Owl Statue Poe",
                "FT West Tile Worm Room Vines Chest",
                "Agitha Male Dragonfly Reward",
                "CitS East Tile Worm Small Chest",
                "PoT Central Tower Chest",
                "Outside AG Poe",
                "OCT South Double Clawshot Chasm Chest",
                "Hyrule Field Amphitheater Owl Statue Chest",
                "SPR Northeast Chandelier Chest",
                "HC West Courtyard North Small Chest",
                "Agitha Female Stag Beetle Reward",
                "LBT West Second Floor Central Small Chest",
                "Agitha Female Mantis Reward",
                "LBT Lobby Rear Chest",
                "Bridge of Eldin Owl Statue Chest",
                "BCT Golden Wolf",
                "Lake Hylia Bridge Cliff Chest",
                "CitS West Garden Lower Chest",
                "GM Outside Clawshot Chest",
                "LLC Fifth Chest",
                "PoT Big Key Chest",
                "Agitha Male Beetle Reward",
                "Desert Campfire East Chest",
                "HC Big Key Chest",
                "ToT Moving Wall Beamos Room Chest",
                "LLC Fourth Chest",
                "LBT East Lower Waterwheel Bridge Chest",
                "CitS East First Wing Chest After Fans",
                "LLC Tenth Chest",
                "LLC Ninth Chest",
                "Kak Watchtower Alcove Chest",
                "BCT Male Butterfly",
                "HC King Bulblin Key",
                "HC East Wing Boomerang Puzzle Chest",
                "PoT Central Outdoor Chest",
                "HC Treasure Room First Small Chest",
                "GM Outside Underwater Chest",
                "LLC Eleventh Chest",
                "Agitha Female Ant Reward",
                "CoO Great Fairy Reward",
                "FT Central Chest Hanging From Web",
                "Lost Woods Waterfall Poe",
                "Kak Graveyard Open Poe",
                "Eldin Field Bomskit Grotto Left Chest",
                "HC West Courtyard Central Small Chest",
                "CitS West Wing Narrow Ledge Chest",
                "SPR Ordon Pumpkin Chest",
                "Skybook From Impaz",
                "STAR Prize 1",
                "HC Treasure Room Fifth Chest",
                "ZD Mother and Child Isle Poe",
                "Ordon Shield",
                "Flight By Fowl Fourth Platform Chest",
                "Goron Springwater Rush",
                "AG Hidden Wall Poe",
                "Agitha Female Dayfly Reward",
                "OCT South Tightrope Chest",
                "Lake Hylia Bridge Bubble Grotto Chest",
                "HC Main Hall Northwest Chest",
                "SPR Ice Room Poe",
                "FT Dungeon Reward",
                "AG Spinner Room Lower Central Small Chest",
                "HC Treasure Room Fifth Small Chest",
                "GM Chest Before Dangoro",
                "Agitha Male Snail Reward",
                "Agitha Male Ant Reward",
                "LBT Before Deku Toad Underwater Left Chest",
                "ToT Poe Above Scales",
                "FT North Deku Like Chest",
                "LBT Central Room Chest",
                "ToT First Staircase Gohma Gate Chest",
                "ToT First Staircase Window Chest",
                "FT Totem Pole Chest",
                "Faron Mist South Chest",
                "LLC Eighth Chest",
                "SPR Lobby Chandelier Chest",
                "LBT Deku Toad Chest",
                "Lake Hylia Dock Poe",
                "Lake Hylia Shell Blade Grotto Chest",
                "FT West Tile Worm Chest Behind Stairs",
                "Renados Letter",
                "LLC Thirteenth Chest",
                "AG Spinner Room First Small Chest",
                "PoT Collect Both Sols",
                "UZR Female Dragonfly",
                "ToT Moving Wall Dinalfos Room Chest",
                "Lanayru Spring Underwater Right Chest",
                "Desert East Canyon Chest",
                "FT Central Chest Behind Stairs",
                "CitS Baba Tower Narrow Ledge Chest",
                "OCT South Golden Wolf",
                "Snowpeak Blizzard Poe",
                "HC Treasure Room Fourth Chest",
                "AG West Poe",
                "AG Torch Room East Chest",
                "ToT Big Key Chest",
                "Lanayru Spring Back Room Right Chest",
                "CitS East Wing Lower Level Chest",
                "LBT West Second Floor Southwest Underwater Chest",
                "Kak Graveyard Golden Wolf",
                "GM Beamos Room Chest",
                "Ashei Sketch",
                "BCT Female Butterfly",
                "Sacred Grove Female Snail",
                "Faron Woods Owl Statue Sky Character",
                "AG Spinner Room Stalfos Alcove Chest",
                "Eldin Stockcave Lowest Chest",
                "Kak Gorge Poe",
                "Lanayru Field Behind Gate Underwater Chest",
                "AG East Lower Turnable Redead Chest",
                "Sacred Grove Male Snail",
                "Eldin Field Stalfos Grotto Left Small Chest",
                "Coro Bottle",
                "LLC Second Poe",
                "LLC Fourteenth Chest",
                "SPR Mansion Map",
                "Flight By Fowl Third Platform Chest",
                "LLC Twelfth Chest",
                "SPR Dungeon Reward",
                "Desert Golden Wolf",
                "Desert Campfire West Chest",
                "LBT West Second Floor Northeast Chest",
                "Desert Female Dayfly",
                "PoT West Wing Chest Behind Wall of Darkness",
                "FT Big Baba Key",
                "Sacred Grove Master Sword Poe",
                "ToT First Staircase Armos Chest",
                "OCT South Fountain Chest",
                "AG Big Key Chest",
                "HC Treasure Room Eighth Small Chest",
                "SPR West Courtyard Buried Chest",
                "CoO Floor 33 Poe",
                "Agitha Male Dayfly Reward",
                "PoT East Wing First Room Zant Head Chest",
                "CitS Big Key Chest",
                "HC Treasure Room Third Small Chest",
                "GM Main Magnet Room Top Chest",
                "Agitha Male Butterfly Reward",
                "OCT South Tektite Grotto Chest",
                "PoT West Wing Second Room Lower South Chest",
                "GM Gor Ebizo Key Shard",
                "Bridge of Eldin Female Phasmid",
                "East CT Bridge Poe",
                "FT Entrance Vines Chest",
                "HC Southeast Balcony Tower Chest",
                "HC Treasure Room Sixth Small Chest",
                "Faron Field Bridge Chest",
                "Death Mountain Trail Poe",
                "SPR Lobby West Armor Chest",
                "Charlo Donation Blessing",
                "SPR Lobby Poe",
                "CitS Aeralfos Chest",
                "Faron Woods Owl Statue Chest",
                "SPR Wooden Beam Chandelier Chest",
                "CitS Argorok Heart Container",
                "HC Graveyard Grave Switch Room Front Left Chest",
                "SPR Courtyard Central Chest",
                "Flight By Fowl Second Platform Chest",
                "Desert Male Dayfly",
                "Desert Northwest Chest Behind Gates",
                "Eldin Spring Underwater Chest",
                "Kak Gorge Owl Statue Chest",
                "CitS West Garden Lone Island Chest",
                "HC Graveyard Grave Switch Room Right Chest",
                "Lanayru Spring West Double Clawshot Chest",
                "SPR Broken Floor Chest",
                "AG Torch Room West Chest",
                "Isle of Riches Poe",
                "GM Crystal Switch Room Underwater Chest",
                "CitS West Wing First Chest",
                "Snowboard Racing Prize",
                "Sacred Grove Baba Serpent Grotto Chest",
                "Lost Woods Boulder Poe",
                "CitS Poe Above Central Fan",
                "Ordon Sword",
                "HC Treasure Room Second Chest",
                "Desert South Chest Behind Wooden Gates",
                "Snowpeak Freezard Grotto Chest",
                "GM Outside Beamos Chest",
                "PoT Zant Heart Container",
                "CT Malo Mart Magic Armor",
                "LBT East Water Supply Clawshot Chest",
                "Jovani House Poe",
                "AG West Chandelier Chest",
                "Hyrule Field Amphitheater Owl Statue Sky Character",
                "CoO Floor 44 Poe",
                "Kak Graveyard Lantern Chest",
                "FT East Tile Worm Chest",
                "Agitha Female Snail Reward",
                "LBT East Water Supply Small Chest",
                "Eldin Field Female Grasshopper",
                "GM Dungeon Reward",
                "AG Death Sword Chest",
                "Lake Hylia Bridge Female Mantis",
                "AG East Upper Turnable Chest",
                "CitS West Wing Baba Balcony Chest",
                "Outside AG Lantern Chest",
                "LBT West Water Supply Small Chest",
                "Faron Mist Cave Open Chest",
                "LBT Lobby Left Chest",
                "Bulblin Guard Key",
                "Lake Hylia Underwater Chest",
                "ToT Armos Antechamber North Chest",
                "LBT Big Key Chest",
                "CitS Chest Below Big Key Chest",
                "Kak Village Female Ant",
                "ToT Poe Behind Gate",
                "Kak Gorge Male Pill Bug",
                "PoT East Wing Second Room Southeast Chest",
                "HC Graveyard Grave Switch Room Back Left Chest",
                "CitS West Garden Ledge Chest",
                "Lake Hylia Bridge Male Mantis",
                "Eldin Stockcave Upper Chest",
                "ToT Floor Switch Puzzle Room Upper Chest",
                "LLC Third Chest",
                "SPR Blizzeta Heart Container",
                "Lanayru Field Spinner Track Chest",
                "Iza Raging Rapids Minigame",
                "AG North Turning Room Chest",
                "Agitha Female Pill Bug Reward",
                "GM Main Magnet Room Bottom Chest",
                "GM Gor Amato Small Chest",
                "ZD Waterfall Poe",
                "FT Diababa Heart Container",
                "AG Spinner Room Second Small Chest",
                "Sacred Grove Spinner Chest",
                "AG West Stalfos West Chest",
                "FT Big Key Chest",
                "Desert Rock Grotto Second Poe",
                "LBT East Second Floor Southwest Chest",
                "ToT Armos Antechamber East Chest",
                "ToT Armogohma Heart Container",
                "SPR West Cannon Room Central Chest",
                "Kak Graveyard Grave Poe",
                "Desert Campfire North Chest",
                "GM Fyrus Heart Container",
                "HC Lantern Staircase Chest",
                "GM Magnet Maze Chest",
                "Barnes Bomb Bag",
                "Eldin Field Bomskit Grotto Lantern Chest",
                "CitS Central Outside Poe Island Chest",
                "STAR Prize 2",
                "CitS West Garden Corner Chest",
                "Death Mountain Alcove Chest",
                "North CT Golden Wolf",
                "FT Second Monkey Under Bridge Chest",
                "Desert West Canyon Chest",
                "Agitha Male Mantis Reward",
                "Lanayru Ice Block Puzzle Cave Chest",
                "CitS West Wing Tile Worm Chest",
                "Fishing Hole Heart Piece",
                "Bridge of Eldin Male Phasmid",
                "FT Windless Bridge Chest",
                "ZD Light All Torches Chest",
                "PoT West Wing Second Room Central Chest",
                "Rutelas Blessing",
                "CitS East Wing After Dinalfos Alcove Chest",
                "Snowpeak Cave Ice Poe",
                "LBT Stalactite Room Chest",
                "ToT Armos Antechamber Statue Chest",
                "CoO Floor 17 Poe",
                "AG West Small Chest Behind Block",
                "ToT Guillotine Chest",
                "Cats Hide and Seek Minigame",
                "GM Entrance Chest",
                "Auru Gift To Fyer",
                "Snowpeak Above Freezard Grotto Poe",
                "LLC First Chest",
                "Flight By Fowl Fifth Platform Chest",
                "Kak Watchtower Chest",
                "Faron Field Corner Grotto Left Chest",
                "Outside Lanayru Spring Left Statue Chest",
                "HV Poe",
                "AG Ghoul Rat Room Chest",
                "Desert East Poe",
                "Bulblin Camp Small Chest in Back of Camp",
                "Ilia Memory Reward",
                "Lanayru Spring Back Room Lantern Chest",
                "Agitha Female Ladybug Reward",
                "PoT West Wing First Room Central Chest",
                "CitS Dungeon Reward",
                "Kak Gorge Owl Statue Sky Character",
                "FT Gale Boomerang",
                "Desert Skulltula Grotto Chest",
                "FT West Deku Like Chest",
                "Agitha Male Stag Beetle Reward",
                "Faron Field Male Beetle",
                "PoT East Wing First Room North Small Chest",
                "Kak Graveyard Male Ant",
                "ToT Scales Upper Chest",
                "Eldin Field Stalfos Grotto Stalfos Chest",
                "Ordon Cat Rescue",
                "LBT Underwater Maze Small Chest",
                "SPR West Cannon Room Corner Chest",
                "Lanayru Spring Underwater Left Chest",
                "Lake Hylia Bridge Owl Statue Chest",
                "Talo Sharpshooting",
                "LBT Central Room Spire Chest",
                "Lake Hylia Bridge Owl Statue Sky Character",
                "Desert North Small Chest Before Bulblin Camp",
                "LBT Chandelier Chest",
                "ZD Extinguish All Torches Chest",
                "LLC End Lantern Chest",
                "ToT Chest Before Darknut",
                "Snowpeak Poe Among Trees",
                "Agitha Male Pill Bug Reward",
                "Herding Goats Reward",
                "Desert North Peahat Poe",
                "SPR Chapel Chest",
                "LBT Dungeon Reward",
                "LLC Sixth Chest",
                "Eldin Field Bomb Rock Chest",
                "Agitha Male Grasshopper Reward",
                "Flight By Fowl Top Platform Reward",
                "Kak Gorge Double Clawshot Chest",
                "Lanayru Field Bridge Poe",
                "Wooden Statue",
                "Fishing Hole Bottle",
                "SPR East Courtyard Chest",
                "Lake Hylia Alcove Poe",
                "Lanayru Field Poe Grotto Right Poe",
                "Desert Owl Statue Sky Character",
                "Desert Owl Statue Chest",
                "PoT Central First Room Chest",
                "SPR Wooden Beam Central Chest",
                "SPR Ball and Chain",
                "Plumm Fruit Balloon Minigame",
                "Kak Gorge Spire Heart Piece",
                "LBT Before Deku Toad Underwater Right Chest",
                "Outside Bulblin Camp Poe",
                "Doctors Office Balcony Chest",
                "Outside Lanayru Spring Right Statue Chest",
                "UZR Poe",
                "Bulblin Camp Poe",
                "HC East Wing Balcony Chest",
                "LLC Seventh Chest",
                "Lanayru Spring East Double Clawshot Chest",
                "Snowpeak Icy Summit Poe",
                "OCT South Poe",
                "ToT Scales Gohma Chest",
                "GM Gor Amato Key Shard",
                "Kak Gorge Female Pill Bug",
                "Eldin Stockcave Lantern Chest",
                "Eldin Lantern Cave Lantern Chest",
                "Agitha Female Butterfly Reward",
                "OCT South Female Ladybug",
                "HC Treasure Room First Chest",
                "Telma Invoice",
                "SPR Wooden Beam Northwest Chest",
                "LBT Before Deku Toad Alcove Chest",
                "Eldin Lantern Cave Poe",
                "Kak Village Malo Mart Hylian Shield",
                "PoT East Wing First Room East Alcove Chest",
                "Bulblin Camp Roasted Boar",
                "Faron Woods Golden Wolf",
                "Jovani 60 Poe Soul Reward",
                "Kak Village Malo Mart Red Potion",
                "Kak Village Malo Mart Wooden Shield",
                "AG Dungeon Reward",
                "Sacred Grove Pedestal Master Sword",
                "Sacred Grove Pedestal Shadow Crystal",
                "CT Goron Shop Hylian Shield",
                "FT Diababa",
                "GM Fyrus",
                "LBT Morpheel",
                "AG Stallord",
                "SPR Blizzeta",
                "ToT Armogohma",
                "CitS Argorok",
                "PoT Zant",
                "HC Ganondorf",
                "South Faron Portal",
                "North Faron Portal",
                "Sacred Grove Portal",
                "Kak Gorge Portal",
                "Kak Village Portal",
                "Death Mountain Portal",
                "Bridge of Eldin Portal",
                "CT Portal",
                "Lake Hylia Portal",
                "ZD Portal",
                "UZR Portal",
                "Snowpeak Portal",
                "Desert Portal",
                "Mirror Chamber Portal",
                "CT Goron Shop Red Potion",
                "CT Goron Shop Lantern Oil",
                "CT Goron Shop Arrow Refill",
                "Kak Village Bell Rupee",
                "Coro Lantern",
                "Coro Gate Key",
                "Shad Dominion Rod",
                "Faron Woods Coro Boulder Rupee 1",
                "Faron Woods Coro Boulder Rupee 2",
                "Faron Woods Coro Boulder Rupee 3",
                "Faron Woods Coro Boulder Rupee 4",
                "Ordon Bo Cliff Rupee",
                "Ordon Bo Roof Rupee",
                "Ordon Bo Window Rupee 1",
                "Ordon Bo Window Rupee 2",
                "Ordon Hidden Rusl House Rupee",
                "Ordon Rupee In Grass By Bo",
                "Ordon Rupee In River 1",
                "Ordon Rupee In River 2",
                "Ordon Rupee Under Bridge",
                "Ordon Rupee Under Tall Tree 1",
                "Ordon Rupee Under Tall Tree 2",
                "Ordon Rusl House Roof Rupee 1",
                "Ordon Rusl House Roof Rupee 2",
                "Ordon Shield House Ledge Grass Rupee",
                "Ordon Tree Long Branch Rupee",
                "Ordon Tree Short Branch Rupee",
                "ZD Behind Waterfall Rupee",
                "ZD Central Underwater Boulder Rupee",
                "ZD North Underwater Boulder Rupee",
                "ZD Shortcut Ledge Rupee",
                "ZD Shortcut Lower Boulder Rupee",
                "ZD Shortcut Upper Boulder Rupee",
                "ZD Throne East Gate Underwater Rupee",
                "ZD Throne East Underwater Rupee",
                "ZD Throne Northwest Underwater Rupee",
                "ZD Throne South Underwater Rupee",
                "ZD Throne West Gate Underwater Rupee",
                "ZD Throne West Underwater Rupee",
                "ZD Top Ledge Rupee",
                "ZD Vine Ledge Rupee",
                "ZD Waterfall Ledge Rupee",
                "UZR East Underwater Boulder Rupee",
                "UZR Central Underwater Boulder Rupee",
                "UZR West Underwater Boulder Rupee",
                "UZR Ledge Boulder Rupee",
                "Kak Graveyard Underwater Boulder Rupee",
                "Eldin Spring Underwater Boulder Rupee",
                "Kak Village Spring Shortcut Box Rupee 1",
                "Kak Village Spring Shortcut Box Rupee 2",
                "Kak Village Ant House Ledge Box Rupee",
                "Kak Village Hot Spring Ledge Box Rupee",
                "Death Mountain Volcano Ledge Rupee 1",
                "Death Mountain Volcano Ledge Rupee 2",
                "Death Mountain Volcano Ledge Rupee 3",
                "Death Mountain Volcano Pipe Ledge Rock Rupee",
                "Lake Hylia Left Underwater Pillar Rupee",
                "Lake Hylia Right Underwater Pillar Rupee",
                "Lake Hylia Right Underwater Boulder Rupee",
                "Lake Hylia Left Underwater Boulder Rupee",
                "Lanayru Spring Upper Underwater Boulder Rupee",
                "Lanayru Spring Lower Underwater Boulder Rupee",
                "Bridge of Eldin Boulder Rupee",
                "Kak Gorge Owl Statue Boulder Rupee",
                "Kak Gorge Spire Boulder Rupee",
                "Lake Hylia Bridge Faron Boulder Rupee",
                "Lake Hylia Bridge Owl Statue Boulder Rupee",
                "Lanayru Field North Spinner Track Boulder Rupee",
                "Lanayru Field South Spinner Track Boulder Rupee",
                "Lanayru Field North Underwater Boulder Rupee",
                "Lanayru Field South Underwater Boulder Rupee",
                "OCT South Boulder Rupee",
                "BCT Northern Boulder Rupee",
                "BCT Southern Boulder Rupee",
                "Lanayru Field Tree Boulder Rupee",
                "Snowboarding Bridge Ledge Bottom Rupee",
                "Snowboarding Bridge Ledge Middle Rupee",
                "Snowboarding Bridge Ledge Upper Rupee",
                "Snowboarding Shortcut Rupee 1",
                "Snowboarding Shortcut Rupee 2",
                "Snowboarding Shortcut Rupee 3",
                "Snowboarding Shortcut Rupee 4",
                "Snowboarding Shortcut Rupee 5",
                "Snowboarding Shortcut Rupee 6",
                "Snowboarding Shortcut Rupee 7",
                "Snowboarding Shortcut Rupee 8",
                "Snowboarding Shortcut Rupee 9",
                "Snowboarding Shortcut Rupee 10",
                "Snowboarding Shortcut Rupee 11",
                "Snowboarding Snowy Tree Top Rupee 1",
                "Snowboarding Snowy Tree Top Rupee 2",
                "Snowboarding Snowy Tree Top Rupee 3",
                "Snowboarding Top Left Rupee",
                "Snowboarding Top Right Rupee",
                "Catch A Greengill",
                "Catch An Ordon Catfish",
                "Catch A Hyrule Bass",
                "Catch A Hylian Pike",
                "Catch A Hylian Loach",
                "Catch A Reekfish",
                "Catch The Legendary Hylian Loach",
                "Rollgoal 1-1",
                "Rollgoal 1-8",
                "Rollgoal 8-8",
                // Add new check names right above this line. The name should
                // match exactly with the json filename in the "Checks"
                // directory.
            };

            nameToId = new(checkNames.Count);
            idNumToName = new(checkNames.Count);

            for (int i = 0; i < checkNames.Count; i++)
            {
                nameToId.Add(checkNames[i], NumToId(i));
                idNumToName.Add(i, checkNames[i]);
            }
        }

        private static string NumToId(int num)
        {
            if (num == 0)
            {
                return idChars.Substring(0, 1);
            }

            List<char> characters = new();
            int currentNum = num;
            while (currentNum > 0)
            {
                int charIndex = currentNum % idChars.Length;
                characters.Add(idChars[charIndex]);
                currentNum -= charIndex;
                currentNum /= idChars.Length;
            }

            characters.Reverse();
            return String.Join("", characters);
        }

        private static int IdToNum(string id)
        {
            string bitStr = "";

            for (int i = 0; i < id.Length; i++)
            {
                bitStr += Convert.ToString(idChars.IndexOf(id[i]), 2).PadLeft(5, '0');
            }

            return Convert.ToInt32(bitStr, 2);
        }

        public static string FromString(string checkName)
        {
            if (nameToId.ContainsKey(checkName))
            {
                return nameToId[checkName];
            }
            return null;
        }

        public static string GetCheckName(int idNumber)
        {
            if (idNumToName.ContainsKey(idNumber))
            {
                return idNumToName[idNumber];
            }
            return null;
        }

        public static int GetCheckIdNum(string checkName)
        {
            if (nameToId.ContainsKey(checkName))
            {
                return IdToNum(nameToId[checkName]);
            }
            return -1;
        }

        public static bool IsValidCheckId(int idNumber)
        {
            return GetCheckName(idNumber) != null;
        }

        public static bool IsValidCheckName(string checkName)
        {
            return GetCheckIdNum(checkName) >= 0;
        }

        // Used to get the list of checks to use in the settings UI for
        // Exclusions and Plando checks. Filters out ones that should not show
        // up such as "FT Diababa"
        public static SortedDictionary<string, int> GetUiNameToIdNumDict()
        {
            SortedDictionary<string, int> nameToIdNum = new();

            foreach (KeyValuePair<string, string> item in nameToId)
            {
                if (!hideFromUiCheckNames.Contains(item.Key))
                    nameToIdNum[item.Key] = IdToNum(item.Value);
            }

            return nameToIdNum;
        }

        public static bool GetIsHideFromUiCheckName(string checkName)
        {
            if (StringUtils.isEmpty(checkName))
                throw new Exception($"checkName was empty.");

            return hideFromUiCheckNames.Contains(checkName);
        }
    }
}
